### ISSUE TITLE
Update Codetabel matrices

### ISSUE THREAD

**Issue by ChandraAlgoe** [Informatievlaanderen/OSLOthema-Waterkwaliteit#10]
Bij de herwerking van DOV-grondmonsters is codetabel matrix hernoemd naar materiaalklasse, dit naar analogie van terminologie in OSLO: https://data.vlaanderen.be/doc/applicatieprofiel/observaties-en-metingen/ontwerpstandaard/2021-08-01/#Monster%3Amateriaalklasse

de codetabel werd aangepast naar een hiërarchische codelijst.
Graag deze velden mee opnemen in tabel matrices.

[
[materiaalklasse_DOV-matrices_OSLO.xlsx](https://github.com/Informatievlaanderen/OSLOthema-Waterkwaliteit/files/10850894/materiaalklasse_DOV-matrices_OSLO.xlsx)
](url)

**Comment by ChandraAlgoe** [comment]
Opnieuw gelogd: https://github.com/Informatievlaanderen/OSLOthema-omgeving/issues/7

**Comment by gezever** [comment]
[materiaal-klasse.txt](https://github.com/Informatievlaanderen/OSLOthema-Waterkwaliteit/files/11679053/materiaal-klasse.txt)
